services:
    proxy-sidecar:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    container_name: proxy-sidecar
    #ports:  # прописывает проброс портов тут
    #  - "3000:3000"
    #  - "8080:8080"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    entrypoint: /bin/sh
    command: 
      - -c
      - |
        GW=$$(ip route | awk '/default/ {print $$3}')
        PROXY_IP=$$(getent hosts host.docker.internal | awk '{print $$1}')
        if [ -z "$$PROXY_IP" ]; then PROXY_IP=$$GW; fi

        ip route add $$PROXY_IP via $$GW dev eth0 || true

        # Настройка Kill Switch
        iptables -F OUTPUT
        iptables -A OUTPUT -o lo -j ACCEPT
        iptables -A OUTPUT -o tun0 -j ACCEPT

        # Ответный трафик для входящих соединений
        iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

        # ДИНАМИЧЕСКИЙ ЦИКЛ IPTABLES ИЗ .ENV
        # Compose заменит ${ALLOWED_HOST_PORTS} при старте, а $$port обработает sh
        for port in $$(echo "${ALLOWED_HOST_PORTS}" | tr ',' ' '); do
          iptables -A OUTPUT -o eth0 -d $$PROXY_IP -p tcp --dport $$port -j ACCEPT
        done

        # Наглухо блокируем остальной исходящий трафик через eth0
        iptables -A OUTPUT -o eth0 -j DROP

        # Подъем TUN и запуск tun2socks
        ip tuntap add mode tun dev tun0
        ip addr add 198.18.0.1/15 dev tun0
        ip link set dev tun0 up
        ip route del default
        ip route add default dev tun0

        exec tun2socks -device tun0 -proxy socks5://$$PROXY_IP:8371 -log info

  opencode:
    container_name: opencode_agent
    build: .
    tty: true
    stdin_open: true
    volumes:
      - ${PATH_FOLDER_WORKSPACE:-./workspace}:/workspace
      - ${OPENCODE_CONFIG:-./root}:/root
      #- C:\proj1:/workspace/proj1
      #- C:\proj2:/workspace/proj2
      #- C:\proj3:/workspace/proj3

    working_dir: /workspace
    env_file:
      - .env
      
    depends_on:
      - proxy-sidecar
    network_mode: "service:proxy-sidecar"

    extra_hosts:
      - "host.docker.internal:host-gateway"